apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ilay1214/quiz_ai_infra
    targetRevision: main
    path: infra/argocd/dev
    directory:
      include: '{external-secrets-operator.yaml,ingress-nginx.yaml,external-secrets-config.yaml}'
      exclude: '{argocd-dev-app.yaml,quiz-ai-dev.yaml,quiz-ai-stage.yaml}' 
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
