apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ilay1214/quiz_ai_infra
    targetRevision: main
    path: infra/argocd/prod
    directory:
      include: '*.yaml'
      exclude: 'app-of-apps.yaml'  # Don't include itself
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
