apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.7.1
    helm:
      releaseName: aws-load-balancer-controller
      values: |
        clusterName: prod-eks-cluster
        region: eu-central-1
        vpcId: ""  # Will use subnet discovery instead
        serviceAccount:
          create: true  # Create ServiceAccount with IRSA annotation
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::505825010815:role/prod-aws-lbc-irsa
        replicaCount: 2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        # Enable subnet autodiscovery via tags
        enableShield: false
        enableWaf: false
        enableWafv2: false
        defaultTargetType: ip
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # kube-system already exists
