apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.7.1
    helm:
      releaseName: aws-load-balancer-controller
      values: |
        clusterName: prod-eks-cluster
        region: eu-central-1
        vpcId: vpc-03807fe482b48ccc3
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::505825010815:role/prod-aws-load-balancer-controller-irsa 
        replicaCount: 2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        # Enable subnet autodiscovery via tags
        enableShield: false
        enableWaf: false
        enableWafv2: false
        defaultTargetType: ip
        createIngressClassResource: true
        ingressClass: alb
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  
      - ServerSideApply=true  
