apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quiz-ai-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # Last, after all infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ilay1214/quiz_ai_infra
    targetRevision: main
    path: infra/quiz-ai-helm
    helm:
      releaseName: quiz-ai
      valueFiles:
        - production_values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: quiz-ai-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
