apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ilay1214/quiz_ai_infra
    targetRevision: main
    path: infra/argocd/prod
    directory:
      recurse: false
      include: '*.yaml'
      exclude: 'root-infra-app.yaml'  # Exclude itself to avoid recursion
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
