apiVersion: v1
kind: Service
metadata:
  name: {{ include "quiz-ai-helm.fullname" . }}-application
  labels:
    {{- include "quiz-ai-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  selector:
    {{- include "quiz-ai-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: application
  ports:
    - name: http
      port: {{ .Values.backend.service.port | default 80 }}
      targetPort: {{ .Values.backend.service.targetPort | default "http" }}
